const columns = [
  { name: "TITLE", uid: "title", sortable: true },
  { name: "CATEGORY", uid: "category"},
  { name: "PER MAR POINTS", uid: "perMarPoints", sortable: true },
  { name: "MAX MAR POINTS", uid: "maxMarPoints", sortable: true },
  { name: "CERTIFICATE DATE", uid: "certificateDate", sortable: true },
  { name: "STUDENT NAME", uid: "name", sortable: true },
  { name: "UNIVERSITY ROLL NO", uid: "universityroll", sortable: true },
  { name: "CLASS ROLL NO", uid: "classroll", sortable: true },
  { name: "EMAIL", uid: "email" },
  { name: "YEAR", uid: "year", sortable: true },
  { name: "MAR STATUS", uid: "status", sortable: true },
  { name: "ACTIONS", uid: "actions" },
];

const statusOptions = [
  { name: "verified", uid: "verified" },
  { name: "pending", uid: "pending" },
  { name: "rejected", uid: "rejected" },
];

const batchOptions = [
    { name: "2020", uid: "2020" },
    { name: "2021", uid: "2021" },
    { name: "2022", uid: "2022" },
    { name: "2023", uid: "2023" },
  ];

const users = [
  {
    universityRollNo: "2205648901",
    classRollNo: "22/CSE-DS/01",
    name: "John Doe",
    email: "john.doe@example.com",
    batch:"2023",
    moocsStatus: "submitted",
  },
  {
    universityRollNo: "2205648902",
    classRollNo: "22/CSE-DS/02",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    batch: "2020",
    moocsStatus: "not submitted",
  },
  {
    universityRollNo: "2205648903",
    classRollNo: "22/CSE-DS/03",
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    batch: "2022",
    moocsStatus: "verified",
  },
  {
    universityRollNo: "2205648904",
    classRollNo: "22/CSE-DS/04",
    name: "Bob Brown",
    email: "bob.brown@example.com",
    batch: 2021,
    moocsStatus: "not submitted",
  },
  {
    universityRollNo: "2205648905",
    classRollNo: "22/CSE-DS/05",
    name: "Emily Wilson",
    email: "emily.wilson@example.com",
    batch:"2023",
    moocsStatus: "submitted",
  },
  {
    universityRollNo: "2205648906",
    classRollNo: "22/CSE-DS/06",
    name: "Michael Davis",
    email: "michael.davis@example.com",
    batch: "2020",
    moocsStatus: "not submitted",
  },
  {
    universityRollNo: "2205648907",
    classRollNo: "22/CSE-DS/07",
    name: "Sophia Martinez",
    email: "sophia.martinez@example.com",
    batch: "2022",
    moocsStatus: "submitted",
  },
  {
    universityRollNo: "2205648908",
    classRollNo: "22/CSE-DS/08",
    name: "William Jones",
    email: "william.jones@example.com",
    batch: "2021",
    moocsStatus: "verified",
  },
  {
    universityRollNo: "2205648909",
    classRollNo: "22/CSE-DS/09",
    name: "Olivia Taylor",
    email: "olivia.taylor@example.com",
    batch:"2023",
    moocsStatus: "not submitted",
  },
  {
    universityRollNo: "2205648910",
    classRollNo: "22/CSE-DS/10",
    name: "Daniel Anderson",
    email: "daniel.anderson@example.com",
    batch: "2020",
    moocsStatus: "submitted",
  },
  {
    universityRollNo: "2205648911",
    classRollNo: "22/CSE-DS/11",
    name: "Ava Wilson",
    email: "ava.wilson@example.com",
    batch: "2022",
    moocsStatus: "not submitted",
  },
  {
    universityRollNo: "2205648912",
    classRollNo: "22/CSE-DS/12",
    name: "James White",
    email: "james.white@example.com",
    batch: "2021",
    moocsStatus: "verified",
  },
  {
    universityRollNo: "2205648913",
    classRollNo: "22/CSE-DS/13",
    name: "Mia Garcia",
    email: "mia.garcia@example.com",
    batch:"2023",
    moocsStatus: "submitted",
  },
  {
    universityRollNo: "2205648914",
    classRollNo: "22/CSE-DS/14",
    name: "Alexander Rodriguez",
    email: "alexander.rodriguez@example.com",
    batch: "2020",
    moocsStatus: "not submitted",
  },
  {
    universityRollNo: "2205648915",
    classRollNo: "22/CSE-DS/15",
    name: "Sofia Hernandez",
    email: "sofia.hernandez@example.com",
    batch: "2022",
    moocsStatus: "verified",
  },
  {
    universityRollNo: "2205648916",
    classRollNo: "22/CSE-DS/16",
    name: "Ethan Martinez",
    email: "ethan.martinez@example.com",
    batch: "2021",
    moocsStatus: "submitted",
  },
  {
    universityRollNo: "2205648917",
    classRollNo: "22/CSE-DS/17",
    name: "Charlotte Wright",
    email: "charlotte.wright@example.com",
    batch:"2023",
    moocsStatus: "not submitted",
  },
  {
    universityRollNo: "2205648918",
    classRollNo: "22/CSE-DS/18",
    name: "Aiden Lewis",
    email: "aiden.lewis@example.com",
    batch: "2020",
    moocsStatus: "submitted",
  },
  {
    universityRollNo: "2205648919",
    classRollNo: "22/CSE-DS/19",
    name: "Amelia Lee",
    email: "amelia.lee@example.com",
    batch: "2022",
    moocsStatus: "not submitted",
  },
  {
    universityRollNo: "2205648920",
    classRollNo: "22/CSE-DS/20",
    name: "Benjamin Turner",
    email: "benjamin.turner@example.com",
    batch: "2021",
    moocsStatus: "verified",
  },
  {
    universityRollNo: "2205648921",
    classRollNo: "22/CSE-DS/21",
    name: "Harper Hall",
    email: "harper.hall@example.com",
    batch:"2023",
    moocsStatus: "submitted",
  },
  {
    universityRollNo: "2205648922",
    classRollNo: "22/CSE-DS/22",
    name: "Sebastian Martinez",
    email: "sebastian.martinez@example.com",
    batch: "2020",
    moocsStatus: "not submitted",
  },
  {
    universityRollNo: "2205648923",
    classRollNo: "22/CSE-DS/23",
    name: "Lily Perez",
    email: "lily.perez@example.com",
    batch: "2022",
    moocsStatus: "verified",
  },
  {
    universityRollNo: "2205648924",
    classRollNo: "22/CSE-DS/24",
    name: "Gabriel Scott",
    email: "gabriel.scott@example.com",
    batch: "2021",
    moocsStatus: "submitted",
  },
  {
    universityRollNo: "2205648925",
    classRollNo: "22/CSE-DS/25",
    name: "Madison Young",
    email: "madison.young@example.com",
    batch:"2023",
    moocsStatus: "not submitted",
  },
  {
    universityRollNo: "2205648926",
    classRollNo: "22/CSE-DS/26",
    name: "Logan King",
    email: "logan.king@example.com",
    batch: "2020",
    moocsStatus: "submitted",
  },
  {
    universityRollNo: "2205648927",
    classRollNo: "22/CSE-DS/27",
    name: "Nora Rivera",
    email: "nora.rivera@example.com",
    batch: "2022",
    moocsStatus: "not submitted",
  },
  {
    universityRollNo: "2205648928",
    classRollNo: "22/CSE-DS/28",
    name: "Lucas Nelson",
    email: "lucas.nelson@example.com",
    batch: "2021",
    moocsStatus: "verified",
  },
  {
    universityRollNo: "2205648929",
    classRollNo: "22/CSE-DS/29",
    name: "Evelyn Carter",
    email: "evelyn.carter@example.com",
    batch:"2023",
    moocsStatus: "submitted",
  },
  {
    universityRollNo: "2205648930",
    classRollNo: "22/CSE-DS/30",
    name: "Jackson Price",
    email: "jackson.price@example.com",
    batch: "2020",
    moocsStatus: "not submitted",
  },
  {
    universityRollNo: "2205648931",
    classRollNo: "22/CSE-DS/31",
    name: "Scarlett Ross",
    email: "scarlett.ross@example.com",
    batch: "2022",
    moocsStatus: "verified",
  },
  {
    universityRollNo: "2205648932",
    classRollNo: "22/CSE-DS/32",
    name: "Elijah Coleman",
    email: "elijah.coleman@example.com",
    batch: "2021",
    moocsStatus: "submitted",
  },
  {
    universityRollNo: "2205648933",
    classRollNo: "22/CSE-DS/33",
    name: "Chloe Stewart",
    email: "chloe.stewart@example.com",
    batch:"2023",
    moocsStatus: "not submitted",
  },
  {
    universityRollNo: "2205648934",
    classRollNo: "22/CSE-DS/34",
    name: "Carter Bell",
    email: "carter.bell@example.com",
    batch: "2020",
    moocsStatus: "submitted",
  },
  {
    universityRollNo: "2205648935",
    classRollNo: "22/CSE-DS/35",
    name: "Grace Long",
    email: "grace.long@example.com",
    batch: "2022",
    moocsStatus: "not submitted",
  },
  {
    universityRollNo: "2205648936",
    classRollNo: "22/CSE-DS/36",
    name: "Lincoln Cook",
    email: "lincoln.cook@example.com",
    batch: "2021",
    moocsStatus: "verified",
  },
  {
    universityRollNo: "2205648937",
    classRollNo: "22/CSE-DS/37",
    name: "Ella Cooper",
    email: "ella.cooper@example.com",
    batch:"2023",
    moocsStatus: "submitted",
  },
  {
    universityRollNo: "2205648938",
    classRollNo: "22/CSE-DS/38",
    name: "Mason Morgan",
    email: "mason.morgan@example.com",
    batch: "2020",
    moocsStatus: "not submitted",
  },
  {
    universityRollNo: "2205648939",
    classRollNo: "22/CSE-DS/39",
    name: "Aria Peterson",
    email: "aria.peterson@example.com",
    batch: "2022",
    moocsStatus: "verified",
  },
  {
    universityRollNo: "2205648940",
    classRollNo: "22/CSE-DS/40",
    name: "Miles Reed",
    email: "miles.reed@example.com",
    batch: "2021",
    moocsStatus: "submitted",
  },
  {
    universityRollNo: "2205648941",
    classRollNo: "22/CSE-DS/41",
    name: "Luna Flores",
    email: "luna.flores@example.com",
    batch:"2023",
    moocsStatus: "not submitted",
  },
  {
    universityRollNo: "2205648942",
    classRollNo: "22/CSE-DS/42",
    name: "Liam Ward",
    email: "liam.ward@example.com",
    batch: "2020",
    moocsStatus: "submitted",
  },
  {
    universityRollNo: "2205648943",
    classRollNo: "22/CSE-DS/43",
    name: "Aurora Wood",
    email: "aurora.wood@example.com",
    batch: "2022",
    moocsStatus: "not submitted",
  },
  {
    universityRollNo: "2205648944",
    classRollNo: "22/CSE-DS/44",
    name: "Henry Brooks",
    email: "henry.brooks@example.com",
    batch: "2021",
    moocsStatus: "verified",
  },
  {
    universityRollNo: "2205648945",
    classRollNo: "22/CSE-DS/45",
    name: "Penelope Hayes",
    email: "penelope.hayes@example.com",
    batch:"2023",
    moocsStatus: "submitted",
  },
  {
    universityRollNo: "2205648946",
    classRollNo: "22/CSE-DS/46",
    name: "Mateo Foster",
    email: "mateo.foster@example.com",
    batch: "2020",
    moocsStatus: "verified",
  },
  {
    universityRollNo: "2205648947",
    classRollNo: "22/CSE-DS/47",
    name: "Nova Reyes",
    email: "nova.reyes@example.com",
    batch: "2022",
    moocsStatus: "verified",
  },
  {
    universityRollNo: "2205648948",
    classRollNo: "22/CSE-DS/48",
    name: "Wyatt Russell",
    email: "wyatt.russell@example.com",
    batch: "2021",
    moocsStatus: "submitted",
  },
  {
    universityRollNo: "2205648949",
    classRollNo: "22/CSE-DS/49",
    name: "Hazel Price",
    email: "hazel.price@example.com",
    batch:"2023",
    moocsStatus: "not submitted",
  },
  {
    universityRollNo: "2205648950",
    classRollNo: "22/CSE-DS/50",
    name: "Levi Phillips",
    email: "levi.phillips@example.com",
    batch: "2020",
    moocsStatus: "submitted",
  },
];

// const users = [
//   {
//     id: 1,
//     name: "Tony Reichert",
//     role: "CEO",
//     team: "Management",
//     status: "done",
//     age: "29",
//     avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
//     email: "tony.reichert@example.com",
//   },
//   {
//     id: 2,
//     name: "Zoey Lang",
//     role: "Tech Lead",
//     team: "Development",
//     status: "submitted",
//     age: "25",
//     avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
//     email: "zoey.lang@example.com",
//   },
//   {
//     id: 3,
//     name: "Jane Fisher",
//     role: "Sr. Dev",
//     team: "Development",
//     status: "done",
//     age: "22",
//     avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
//     email: "jane.fisher@example.com",
//   },
//   {
//     id: 4,
//     name: "William Howard",
//     role: "C.M.",
//     team: "Marketing",
//     status: "rejected",
//     age: "28",
//     avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
//     email: "william.howard@example.com",
//   },
//   {
//     id: 5,
//     name: "Kristen Copper",
//     role: "S. Manager",
//     team: "Sales",
//     status: "done",
//     age: "24",
//     avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
//     email: "kristen.cooper@example.com",
//   },
//   {
//     id: 6,
//     name: "Brian Kim",
//     role: "P. Manager",
//     team: "Management",
//     age: "29",
//     avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
//     email: "brian.kim@example.com",
//     status: "done",
//   },
//   {
//     id: 7,
//     name: "Michael Hunt",
//     role: "Designer",
//     team: "Design",
//     status: "submitted",
//     age: "27",
//     avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
//     email: "michael.hunt@example.com",
//   },
//   {
//     id: 8,
//     name: "Samantha Brooks",
//     role: "HR Manager",
//     team: "HR",
//     status: "done",
//     age: "31",
//     avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
//     email: "samantha.brooks@example.com",
//   },
//   {
//     id: 9,
//     name: "Frank Harrison",
//     role: "F. Manager",
//     team: "Finance",
//     status: "rejected",
//     age: "33",
//     avatar: "https://i.pravatar.cc/150?img=4",
//     email: "frank.harrison@example.com",
//   },
//   {
//     id: 10,
//     name: "Emma Adams",
//     role: "Ops Manager",
//     team: "Operations",
//     status: "done",
//     age: "35",
//     avatar: "https://i.pravatar.cc/150?img=5",
//     email: "emma.adams@example.com",
//   },
//   {
//     id: 11,
//     name: "Brandon Stevens",
//     role: "Jr. Dev",
//     team: "Development",
//     status: "done",
//     age: "22",
//     avatar: "https://i.pravatar.cc/150?img=8",
//     email: "brandon.stevens@example.com",
//   },
//   {
//     id: 12,
//     name: "Megan Richards",
//     role: "P. Manager",
//     team: "Product",
//     status: "submitted",
//     age: "28",
//     avatar: "https://i.pravatar.cc/150?img=10",
//     email: "megan.richards@example.com",
//   },
//   {
//     id: 13,
//     name: "Oliver Scott",
//     role: "S. Manager",
//     team: "Security",
//     status: "done",
//     age: "37",
//     avatar: "https://i.pravatar.cc/150?img=12",
//     email: "oliver.scott@example.com",
//   },
//   {
//     id: 14,
//     name: "Grace Allen",
//     role: "M. Specialist",
//     team: "Marketing",
//     status: "done",
//     age: "30",
//     avatar: "https://i.pravatar.cc/150?img=16",
//     email: "grace.allen@example.com",
//   },
//   {
//     id: 15,
//     name: "Noah Carter",
//     role: "IT Specialist",
//     team: "I. Technology",
//     status: "submitted",
//     age: "31",
//     avatar: "https://i.pravatar.cc/150?img=15",
//     email: "noah.carter@example.com",
//   },
//   {
//     id: 16,
//     name: "Ava Perez",
//     role: "Manager",
//     team: "Sales",
//     status: "done",
//     age: "29",
//     avatar: "https://i.pravatar.cc/150?img=20",
//     email: "ava.perez@example.com",
//   },
//   {
//     id: 17,
//     name: "Liam Johnson",
//     role: "Data Analyst",
//     team: "Analysis",
//     status: "done",
//     age: "28",
//     avatar: "https://i.pravatar.cc/150?img=33",
//     email: "liam.johnson@example.com",
//   },
//   {
//     id: 18,
//     name: "Sophia Taylor",
//     role: "QA Analyst",
//     team: "Testing",
//     status: "done",
//     age: "27",
//     avatar: "https://i.pravatar.cc/150?img=29",
//     email: "sophia.taylor@example.com",
//   },
//   {
//     id: 19,
//     name: "Lucas Harris",
//     role: "Administrator",
//     team: "Information Technology",
//     status: "done",
//     age: "32",
//     avatar: "https://i.pravatar.cc/150?img=50",
//     email: "lucas.harris@example.com",
//   },
//   {
//     id: 20,
//     name: "Mia Robinson",
//     role: "Coordinator",
//     team: "Operations",
//     status: "done",
//     age: "26",
//     avatar: "https://i.pravatar.cc/150?img=45",
//     email: "mia.robinson@example.com",
//   },
// ];

export { columns, users, statusOptions,batchOptions };
